package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Nicolás
 */
public class Vista extends JFrame
{

    public Vista()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBusqueda = new ButtonGroup();
        grupoRecorrido = new ButtonGroup();
        grupoCreacionGrafo = new ButtonGroup();
        jSplitPane1 = new JSplitPane();
        jScrollPane1 = new JScrollPane();
        panelGraficoGrafo = new JPanel();
        jPanel6 = new JPanel();
        jPanel7 = new JPanel();
        jPanel3 = new JPanel();
        jButton4 = new JButton();
        jButton5 = new JButton();
        jPanel4 = new JPanel();
        jButton6 = new JButton();
        jButton7 = new JButton();
        jPanel1 = new JPanel();
        jComboBox1 = new JComboBox<>();
        jButton1 = new JButton();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jComboBox2 = new JComboBox<>();
        jTextField1 = new JTextField();
        jLabel2 = new JLabel();
        jButton2 = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafos!");
        setMinimumSize(new Dimension(800, 600));
        setPreferredSize(new Dimension(840, 620));

        jSplitPane1.setDividerLocation(280);

        panelGraficoGrafo.setBackground(new Color(255, 255, 255));
        panelGraficoGrafo.setMinimumSize(new Dimension(0, 0));
        panelGraficoGrafo.setPreferredSize(new Dimension(0, 0));
        panelGraficoGrafo.setLayout(new BorderLayout());
        jScrollPane1.setViewportView(panelGraficoGrafo);

        jSplitPane1.setRightComponent(jScrollPane1);

        jPanel6.setLayout(new BorderLayout());

        jPanel7.setBackground(new Color(255, 255, 255));
        jPanel7.setBorder(BorderFactory.createTitledBorder(null, "Edición", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 0, 12), new Color(38, 156, 144))); // NOI18N
        jPanel7.setMinimumSize(new Dimension(280, 70));
        jPanel7.setPreferredSize(new Dimension(260, 280));
        jPanel7.setLayout(null);

        jPanel3.setBackground(new Color(255, 255, 255));
        jPanel3.setBorder(BorderFactory.createTitledBorder(null, "Aristas", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 0, 12), new Color(38, 166, 154))); // NOI18N
        jPanel3.setLayout(null);

        jButton4.setIcon(new ImageIcon("C:\\Users\\Equipo1\\Desktop\\Material\\Button+Green1.png")); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton4.setPressedIcon(new ImageIcon("C:\\Users\\Equipo1\\Desktop\\Material\\Button+Green2.png")); // NOI18N
        jPanel3.add(jButton4);
        jButton4.setBounds(60, 30, 57, 57);

        jButton5.setIcon(new ImageIcon("C:\\Users\\Equipo1\\Desktop\\Material\\Button+RedNew1.png")); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton5.setPressedIcon(new ImageIcon("C:\\Users\\Equipo1\\Desktop\\Material\\Button+RedNew2.png")); // NOI18N
        jButton5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(160, 30, 57, 57);

        jPanel7.add(jPanel3);
        jPanel3.setBounds(0, 110, 280, 110);

        jPanel4.setBackground(new Color(255, 255, 255));
        jPanel4.setBorder(BorderFactory.createTitledBorder(null, "Vértices", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 0, 12), new Color(38, 166, 154))); // NOI18N
        jPanel4.setLayout(null);

        jButton6.setIcon(new ImageIcon("C:\\Users\\Equipo1\\Desktop\\Material\\Button+Green1.png")); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton6.setPressedIcon(new ImageIcon("C:\\Users\\Equipo1\\Desktop\\Material\\Button+Green2.png")); // NOI18N
        jPanel4.add(jButton6);
        jButton6.setBounds(60, 30, 57, 57);

        jButton7.setIcon(new ImageIcon("C:\\Users\\Equipo1\\Desktop\\Material\\Button+RedNew1.png")); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton7.setPressedIcon(new ImageIcon("C:\\Users\\Equipo1\\Desktop\\Material\\Button+RedNew2.png")); // NOI18N
        jButton7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(160, 30, 57, 57);

        jPanel7.add(jPanel4);
        jPanel4.setBounds(0, 0, 280, 110);

        jPanel6.add(jPanel7, BorderLayout.CENTER);

        jPanel1.setBackground(new Color(255, 255, 255));
        jPanel1.setBorder(BorderFactory.createTitledBorder(null, "Creación del grafo", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 0, 12), new Color(38, 166, 154))); // NOI18N
        jPanel1.setMinimumSize(new Dimension(22, 150));
        jPanel1.setPreferredSize(new Dimension(22, 80));
        jPanel1.setLayout(null);

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new Font("Dialog", 0, 12)); // NOI18N
        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Matriz de adyacencia", "Lista de adyacencia" }));
        jComboBox1.setBorder(BorderFactory.createTitledBorder(null, "Tipo de grafo", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 0, 11), new Color(255, 141, 141))); // NOI18N
        jComboBox1.setFocusable(false);
        jComboBox1.setOpaque(false);
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(10, 20, 150, 50);

        jButton1.setBackground(new Color(38, 166, 154));
        jButton1.setFont(new Font("Dialog", 0, 14)); // NOI18N
        jButton1.setForeground(new Color(255, 255, 255));
        jButton1.setText("Crear");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 37, 100, 30);

        jPanel6.add(jPanel1, BorderLayout.PAGE_START);

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setBorder(BorderFactory.createTitledBorder(null, "Busquedas", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 0, 12), new Color(38, 166, 154))); // NOI18N
        jPanel2.setPreferredSize(new Dimension(22, 280));
        jPanel2.setLayout(null);

        jLabel1.setFont(new Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new Color(255, 141, 141));
        jLabel1.setText("Vértice:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 50, 50, 16);

        jComboBox2.setEditable(true);
        jComboBox2.setFont(new Font("Dialog", 0, 12)); // NOI18N
        jComboBox2.setModel(new DefaultComboBoxModel<>(new String[] { "Anchura", "Profundidad" }));
        jComboBox2.setBorder(null);
        jComboBox2.setFocusable(false);
        jComboBox2.setOpaque(false);
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(140, 20, 130, 20);

        jTextField1.setText(" ");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(60, 50, 90, 30);

        jLabel2.setFont(new Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new Color(255, 141, 141));
        jLabel2.setText("Tipo de búsqueda:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 20, 120, 16);

        jButton2.setBackground(new Color(38, 166, 154));
        jButton2.setFont(new Font("Dialog", 0, 14)); // NOI18N
        jButton2.setForeground(new Color(255, 255, 255));
        jButton2.setText("Buscar");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jPanel2.add(jButton2);
        jButton2.setBounds(160, 50, 110, 30);

        jPanel6.add(jPanel2, BorderLayout.PAGE_END);

        jSplitPane1.setLeftComponent(jPanel6);

        getContentPane().add(jSplitPane1, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed


    public ButtonGroup getGrupoBusqueda()
    {
        return grupoBusqueda;
    }

    public ButtonGroup getGrupoCreacionGrafo()
    {
        return grupoCreacionGrafo;
    }

    public ButtonGroup getGrupoRecorrido()
    {
        return grupoRecorrido;
    }

    public JPanel getPanelGraficoGrafo()
    {
        return panelGraficoGrafo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup grupoBusqueda;
    private ButtonGroup grupoCreacionGrafo;
    private ButtonGroup grupoRecorrido;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton4;
    private JButton jButton5;
    private JButton jButton6;
    private JButton jButton7;
    private JComboBox<String> jComboBox1;
    private JComboBox<String> jComboBox2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JScrollPane jScrollPane1;
    private JSplitPane jSplitPane1;
    private JTextField jTextField1;
    private JPanel panelGraficoGrafo;
    // End of variables declaration//GEN-END:variables
}
